"use client";

import React from "react";
import type { LucideProps } from "lucide-react";
// v2.4 (أداء): استيراد أسماء محددة بدل import * — كان يجرّ مكتبة lucide كاملة
// (~508kB chunk) إلى كل صفحة. الخريطة تُبنى من الأسماء المستخدمة فعليًا في
// الكود؛ اسم غير معروف يعرض فراغًا (نفس سلوك النسخة السابقة تمامًا).
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  Badge,
  Baseline,
  Bell,
  Bold,
  Box,
  Boxes,
  Briefcase,
  Building2,
  CalendarCheck,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  CircleSlash,
  Clipboard,
  ClipboardList,
  Clock,
  Code,
  Compass,
  Construction,
  Contact,
  Cpu,
  CreditCard,
  Currency,
  Database,
  Delete,
  Download,
  Edit,
  Ellipsis,
  Eye,
  File,
  FileCode,
  FileDown,
  FilePlus,
  FileText,
  FileUp,
  Filter,
  Flag,
  Folder,
  FolderPlus,
  Folders,
  Gauge,
  Gem,
  Ghost,
  GitBranch,
  Github,
  Grid,
  Hand,
  HelpCircle,
  History,
  Home,
  Info,
  KeyRound,
  Landmark,
  Languages,
  LayoutDashboard,
  LayoutGrid,
  Lightbulb,
  Linkedin,
  ListChecks,
  Loader,
  LoaderCircle,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MailCheck,
  Maximize2,
  Menu,
  MessageCircle,
  MessageCircleQuestion,
  Minus,
  Moon,
  Pencil,
  Percent,
  Phone,
  Pill,
  Play,
  Plus,
  Pointer,
  Printer,
  Receipt,
  RefreshCw,
  Rocket,
  RotateCcw,
  RotateCw,
  Save,
  Scale,
  ScanSearch,
  Scroll,
  Search,
  SearchX,
  Section,
  Send,
  Server,
  Settings,
  ShieldCheck,
  Sparkles,
  StickyNote,
  Sun,
  Table,
  Target,
  Text,
  ToggleRight,
  Trash2,
  Twitter,
  Type,
  Upload,
  User,
  UserPlus,
  UserSearch,
  Users,
  View,
  Wallet,
  WandSparkles,
  X,
} from "lucide-react";

export interface IconProps {
  /** Lucide icon name in kebab-case, e.g. "layout-dashboard". */
  name: string;
  size?: number;
  color?: string;
  strokeWidth?: number;
  style?: React.CSSProperties;
}

const ICONS: Record<string, React.ComponentType<LucideProps>> = {
  "activity": Activity,
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "arrow-up-down": ArrowUpDown,
  "badge": Badge,
  "baseline": Baseline,
  "bell": Bell,
  "bold": Bold,
  "box": Box,
  "boxes": Boxes,
  "briefcase": Briefcase,
  "building-2": Building2,
  "calendar-check": CalendarCheck,
  "check": Check,
  "check-circle": CheckCircle,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "chevrons-up-down": ChevronsUpDown,
  "circle-slash": CircleSlash,
  "clipboard": Clipboard,
  "clipboard-list": ClipboardList,
  "clock": Clock,
  "code": Code,
  "compass": Compass,
  "construction": Construction,
  "contact": Contact,
  "cpu": Cpu,
  "credit-card": CreditCard,
  "currency": Currency,
  "database": Database,
  "delete": Delete,
  "download": Download,
  "edit": Edit,
  "ellipsis": Ellipsis,
  "eye": Eye,
  "file": File,
  "file-code": FileCode,
  "file-down": FileDown,
  "file-plus": FilePlus,
  "file-text": FileText,
  "file-up": FileUp,
  "filter": Filter,
  "flag": Flag,
  "folder": Folder,
  "folder-plus": FolderPlus,
  "folders": Folders,
  "gauge": Gauge,
  "gem": Gem,
  "ghost": Ghost,
  "git-branch": GitBranch,
  "github": Github,
  "grid": Grid,
  "hand": Hand,
  "help-circle": HelpCircle,
  "history": History,
  "home": Home,
  "info": Info,
  "key-round": KeyRound,
  "landmark": Landmark,
  "languages": Languages,
  "layout-dashboard": LayoutDashboard,
  "layout-grid": LayoutGrid,
  "lightbulb": Lightbulb,
  "linkedin": Linkedin,
  "list-checks": ListChecks,
  "loader": Loader,
  "loader-circle": LoaderCircle,
  "lock": Lock,
  "log-in": LogIn,
  "log-out": LogOut,
  "mail": Mail,
  "mail-check": MailCheck,
  "maximize-2": Maximize2,
  "menu": Menu,
  "message-circle": MessageCircle,
  "message-circle-question": MessageCircleQuestion,
  "minus": Minus,
  "moon": Moon,
  "pencil": Pencil,
  "percent": Percent,
  "phone": Phone,
  "pill": Pill,
  "play": Play,
  "plus": Plus,
  "pointer": Pointer,
  "printer": Printer,
  "receipt": Receipt,
  "refresh-cw": RefreshCw,
  "rocket": Rocket,
  "rotate-ccw": RotateCcw,
  "rotate-cw": RotateCw,
  "save": Save,
  "scale": Scale,
  "scan-search": ScanSearch,
  "scroll": Scroll,
  "search": Search,
  "search-x": SearchX,
  "section": Section,
  "send": Send,
  "server": Server,
  "settings": Settings,
  "shield-check": ShieldCheck,
  "sparkles": Sparkles,
  "sticky-note": StickyNote,
  "sun": Sun,
  "table": Table,
  "target": Target,
  "text": Text,
  "toggle-right": ToggleRight,
  "trash-2": Trash2,
  "twitter": Twitter,
  "type": Type,
  "upload": Upload,
  "user": User,
  "user-plus": UserPlus,
  "user-search": UserSearch,
  "users": Users,
  "view": View,
  "wallet": Wallet,
  "wand-sparkles": WandSparkles,
  "x": X,
};

/**
 * Thin wrapper over lucide-react that accepts kebab-case names (as the
 * design prototypes use) and centers the glyph in an inline-flex box.
 */
export function Icon({ name, size = 18, color, strokeWidth = 1.75, style }: IconProps) {
  const Cmp = ICONS[name];
  return (
    <span
      style={{
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        flex: "0 0 auto",
        color,
        ...style,
      }}
    >
      {Cmp ? <Cmp size={size} strokeWidth={strokeWidth} /> : null}
    </span>
  );
}
